# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

"""
Calendar provider using xtdata trading calendar.
"""

from __future__ import annotations

from typing import List

import pandas as pd

from qlib.data.data import CalendarProvider
from qlib.log import get_module_logger

logger = get_module_logger("XtQMTCalendarProvider")


class XtQMTCalendarProvider(CalendarProvider):
    """Calendar provider backed by xtdata trading calendar.

    Useful for live trading to ensure calendar is always up-to-date.
    For backtesting, the calendar generated by data_collector.py is preferred.
    """

    def __init__(self):
        try:
            from xtquant import xtdata
            self.xtdata = xtdata
        except ImportError:
            raise ImportError("xtquant is required for XtQMTCalendarProvider.")

    def load_calendar(self, freq, future):
        """Load trading calendar from xtdata.

        Parameters
        ----------
        freq : str
            Frequency (only "day" is supported via xtdata trading days).
        future : bool
            Whether to include future trading days.

        Returns
        -------
        list
            List of pd.Timestamp.
        """
        try:
            trading_dates = self.xtdata.get_trading_calendar("SH")
        except (AttributeError, TypeError):
            # Fallback for older xtquant versions
            trading_dates = self.xtdata.get_trading_dates_by_count("SH", -1, 10000)

        if not trading_dates:
            logger.warning("No trading dates returned from xtdata")
            return []

        calendar = [pd.Timestamp(d) for d in sorted(trading_dates)]
        return calendar
